name: flutter_mmkv
description: A Flutter plugin to use MMKV which is an efficient, small mobile key-value storage framework developed by WeChat.
version: 1.2.0
author: Muhammad Iqbal <iqbalmineraltown@gmail.com>
homepage: https://github.com/iqbalmineraltown/flutter_mmkv

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.yasincidem.fluttermmkv
    pluginClass: FlutterMmkvPlugin
